// Station fare calculator and determiner.

// utility function
function pad (n, width, z) {
    z = z || '0';
    n = n + '';
    return n.length >= width ? n : new Array(width - n.length + 1).join(z) + n;}

function makeElementAndAttach(targetElement, elementType, text, id) {
    var newElement = document.createElement(elementType)
    if (id) {
        newElement.setAttribute("id", id)}
    newElement.appendChild(
        document.createTextNode(text || ""))
    targetElement.appendChild(newElement)}

var stations = {
    stationList: [
        // The master list of stations.
        // Use to fill up the table and the dropdown.
        {"id": "LBA_01",
         "displayCode": "LBA 01",
         "numberCode": 1001,
         "GMF_LAT": "Szüxjlyŋ",
         "GMF_CYR": "Сӱъйлың",
         "MQY_KMS": "水寧",
         "MQY_HGL": "츄·링.",
         "MQY_LAT": "Jyuu Lingr"},
        {"id": "LBA_02",
         "displayCode": "LBA 02",
         "numberCode": 1002,
         "GMF_LAT": "Qopytal ə'Lejszitszan",
         "GMF_CYR": "Ӄопытал ә'Лейситсан",
         "MQY_KMS": "李時珍醫院",
         "MQY_HGL": "러·치.싼이윤.",
         "MQY_LAT": "Lee Jir Zan I Yunr"},
        {"id": "LBA_03",
         "displayCode": "LBA 03",
         "numberCode": 1003,
         "GMF_LAT": "Qanqyŋ",
         "GMF_CYR": "Ӄанӄың",
         "MQY_KMS": "恆興",
         "MQY_HGL": "항.힝",
         "MQY_LAT": "Hangr Hing"},
        {"id": "LBA_04",
         "displayCode": "LBA 04",
         "numberCode": 1004,
         "GMF_LAT": "Szàjszyŋ",
         "GMF_CYR": "Саъйсың",
         "MQY_KMS": "西城",
         "MQY_HGL": "샤칭:",
         "MQY_LAT": "Sya Jiingr"},
        {"id": "LBA_05",
         "displayCode": "LBA 05",
         "numberCode": 1005,
         "GMF_LAT": "ð'Pazar",
         "GMF_CYR": "ҙ'Пазар",
         "MQY_KMS": "順德",
         "MQY_HGL": "쭌닥",
         "MQY_LAT": "Jjun Dag"},
        {"id": "LBA_06",
         "displayCode": "LBA 06",
         "numberCode": 1006,
         "GMF_LAT": "Jünivèrsytþi ə'Ùzje",
         "GMF_CYR": "Йӱнивеършытѳи ә'Уъзйе",
         "MQY_KMS": "은칭:유니바·시.티.",
         "MQY_HGL": "은칭:/유니바·",
         "MQY_LAT": "Vn Jiingr/UNB"},
        {"id": "LBA_07",
         "displayCode": "LBA 07",
         "numberCode": 1007,
         "GMF_LAT": "Piər",
         "GMF_CYR": "Пиәр",
         "MQY_KMS": "碼頭",
         "MQY_HGL": "마.타.",
         "MQY_LAT": "Mar Tar"},
        {"id": "LBA_08",
         "displayCode": "LBA 08",
         "numberCode": 1008,
         "GMF_LAT": "Wokwan",
         "GMF_CYR": "Ўокўан",
         "MQY_KMS": "鑊灣",
         "MQY_HGL": "꼭깐",
         "MQY_LAT": "Qog Qan"},
        {"id": "LBA_09",
         "displayCode": "LBA 09",
         "numberCode": 1009,
         "GMF_LAT": "Wokwànkjü",
         "GMF_CYR": "Ўокўаънкйӱ",
         "MQY_KMS": "鑊灣橋",
         "MQY_HGL": "꼭깐쿄·",
         "MQY_LAT": "Qog Qan Kyoo"},
        {"id": "LBA_10",
         "displayCode": "LBA 10",
         "numberCode": 1010,
         "GMF_LAT": "Quŋcuŋ",
         "GMF_CYR": "Ӄуңчуң",
         "MQY_KMS": "紅涌",
         "MQY_HGL": "훙.쭝.",
         "MQY_LAT": "Hungr Jjungr"},
        {"id": "LBA_11",
         "displayCode": "LBA 11",
         "numberCode": 1011,
         "GMF_LAT": "Tòwva",
         "GMF_CYR": "Тоъўва",
         "MQY_KMS": "土華",
         "MQY_HGL": "토·까.",
         "MQY_LAT": "Too Qar"},
        {"id": "LBA_12",
         "displayCode": "LBA 12",
         "numberCode": 1012,
         "GMF_LAT": "Lèjtin",
         "GMF_CYR": "Леъйтин",
         "MQY_KMS": "梨田",
         "MQY_HGL": "러틴.",
         "MQY_LAT": "Le Tinr"},
        {"id": "LBA_13",
         "displayCode": "LBA 13",
         "numberCode": 1013,
         "GMF_LAT": "Nel ə'Arzeqt",
         "GMF_CYR": "Нел ә'Арзеӄт",
         "MQY_KMS": "銀町",
         "MQY_HGL": "ᅌᅳᆫ.딩",
         "MQY_LAT": "Ngvnr Ding"},
        {"id": "LBA_14",
         "displayCode": "LBA 14",
         "numberCode": 1014,
         "GMF_LAT": "Szöŋan",
         "GMF_CYR": "Сӧңан",
         "MQY_KMS": "常安",
         "MQY_HGL": "승.온",
         "MQY_LAT": "Svngr On"},
        {"id": "LBA_15",
         "displayCode": "LBA 15",
         "numberCode": 1015,
         "GMF_LAT": "Nel ə'Ilekcrysz",
         "GMF_CYR": "Нел ә'Илекчрыс",
         "MQY_KMS": "電器町",
         "MQY_HGL": "던키딩.",
         "MQY_LAT": "Den Ki dingr"},
        {"id": "LBA_16",
         "displayCode": "LBA 16",
         "numberCode": 1016,
         "GMF_LAT": "Ŋabgeŋ",
         "GMF_CYR": "Ңабгең",
         "MQY_KMS": "鴨頸",
         "MQY_HGL": "ᅌᅡᆸ겅",
         "MQY_LAT": "Ngab Geng"},
        {"id": "LBA_17",
         "displayCode": "LBA 17",
         "numberCode": 1017,
         "GMF_LAT": "Bejfuŋ",
         "GMF_CYR": "Бейфуң",
         "MQY_KMS": "避風灣",
         "MQY_HGL": "버풍깐",
         "MQY_LAT": "Be Pung Qan"},
        {"id": "LBA_18",
         "displayCode": "LBA 18",
         "numberCode": 1018,
         "GMF_LAT": "Gafnəq ð'Qaws",
         "GMF_CYR": "Гафнәӄ ҙ'Ӄаўш",
         "MQY_KMS": "政府大樓",
         "MQY_HGL": "찡.푸댜로·",
         "MQY_LAT": "Jjingr Pu Dya Loo"},
        {"id": "LBA_19",
         "displayCode": "LBA 19",
         "numberCode": 1019,
         "GMF_LAT": "Dỳŋwan",
         "GMF_CYR": "Дыъңўан",
         "MQY_KMS": "釘灣",
         "MQY_HGL": "덩깐",
         "MQY_LAT": "Deng Qan"},
        {"id": "LBA_20",
         "displayCode": "LBA 20",
         "numberCode": 1020,
         "GMF_LAT": "Tùŋpaw",
         "GMF_CYR": "Туъңпаў",
         "MQY_KMS": "東炮",
         "MQY_HGL": "동파.",
         "MQY_LAT": "Dong Par"},
        {"id": "LBA_21",
         "displayCode": "LBA 21",
         "numberCode": 1021,
         "GMF_LAT": "Boan",
         "GMF_CYR": "Боан",
         "MQY_KMS": "寶安",
         "MQY_HGL": "보·온치",
         "MQY_LAT": "Boo On Ji"},
        {"id": "LBA_22",
         "displayCode": "LBA 22",
         "numberCode": 1022,
         "GMF_LAT": "Nel ə'Qemen",
         "GMF_CYR": "Нел ә'Ӄемен",
         "MQY_KMS": "喜門町",
         "MQY_HGL": "허·문.딩",
         "MQY_LAT": "Hee Munr Ding"},
        {"id": "LBA_23",
         "displayCode": "LBA 23",
         "numberCode": 1023,
         "GMF_LAT": "Qəŋtan",
         "GMF_CYR": "Ӄәңтан",
         "MQY_KMS": "杏壇",
         "MQY_HGL": "항탄.",
         "MQY_LAT": "Hang Tanr"},
        {"id": "LSB_01",
         "displayCode": "LSB 01",
         "numberCode": 2001,
         "GMF_LAT": "Qopytal ə'Lejszitszan",
         "GMF_CYR": "Ӄопытал ә'Лейситсан",
         "MQY_KMS": "李時珍醫院",
         "MQY_HGL": "러·치.싼이윤.",
         "MQY_LAT": "Lee Jir Zan I Yunr"},
        {"id": "LSB_02",
         "displayCode": "LSB 02",
         "numberCode": 2002,
         "GMF_LAT": "Szànlyŋ",
         "GMF_CYR": "Саънлың",
         "MQY_KMS": "山寧",
         "MQY_HGL": "찬·링.",
         "MQY_LAT": "Jaan Lingr"},
        {"id": "LSB_03",
         "displayCode": "LSB 03",
         "numberCode": 2003,
         "GMF_LAT": "Ð'TÞEK",
         "GMF_CYR": "Ҙ'ТѲЕК",
         "MQY_KMS": "科技港",
         "MQY_HGL": "포거.공",
         "MQY_LAT": "Po Ger Gong"},
        {"id": "LSB_04",
         "displayCode": "LSB 04",
         "numberCode": 2004,
         "GMF_LAT": "Gajmej",
         "GMF_CYR": "Гаймей",
         "MQY_KMS": "雞尾湖",
         "MQY_HGL": "갸머:꾸.",
         "MQY_LAT": "Gya Meer Qur"},
        {"id": "LSB_05",
         "displayCode": "LSB 05",
         "numberCode": 2005,
         "GMF_LAT": "Ùqdərsetþàlə",
         "GMF_CYR": "Уъӄдәршетѳаълә",
         "MQY_KMS": "海底世界",
         "MQY_HGL": "호·댜.서카이.",
         "MQY_LAT": "Hoo Dyar Se Ka Ir"},
        {"id": "LSB_06",
         "displayCode": "LSB 06",
         "numberCode": 2006,
         "GMF_LAT": "Qył ə'Manqaŋ",
         "GMF_CYR": "Ӄыљ ә'Манӄаң",
         "MQY_KMS": "萬恒",
         "MQY_HGL": "만항.",
         "MQY_LAT": "Man Hangr"},
        {"id": "LSB_07",
         "displayCode": "LSB 07",
         "numberCode": 2007,
         "GMF_LAT": "Kəlanbləqtwo",
         "GMF_CYR": "Кәланбләӄтўо",
         "MQY_KMS": "新크.름뱌.村",
         "MQY_HGL": "슨크.름뱌.쭌",
         "MQY_LAT": "Svn Kvr Lvm Byar Jjun"},
        {"id": "LSO_01",
         "displayCode": "LSO 01",
         "numberCode": 3001,
         "GMF_LAT": "Dỳŋwan",
         "GMF_CYR": "Дыъңўан",
         "MQY_KMS": "釘灣",
         "MQY_HGL": "덩깐",
         "MQY_LAT": "Deng Qan"},
        {"id": "LSO_02",
         "displayCode": "LSO 02",
         "numberCode": 3002,
         "GMF_LAT": "Tùŋpaw",
         "GMF_CYR": "Туъңпаў",
         "MQY_KMS": "東炮",
         "MQY_HGL": "동파.",
         "MQY_LAT": "Dong Par"},
        {"id": "LSO_03",
         "displayCode": "LSO 03",
         "numberCode": 3003,
         "GMF_LAT": "Szamjügwan",
         "GMF_CYR": "Самйӱгўан",
         "MQY_KMS": "衫魚關",
         "MQY_HGL": "삼유.ᄸᅡᆫ",
         "MQY_LAT": "Sam Yur Quan"},
        {"id": "LSO_04",
         "displayCode": "LSO 04",
         "numberCode": 3004,
         "GMF_LAT": "Waŋmaw",
         "GMF_CYR": "Ўаңмаў",
         "MQY_KMS": "宏貿",
         "MQY_HGL": "끙.마·",
         "MQY_LAT": "Qvngr Maa"},
        {"id": "LSO_05",
         "displayCode": "LSO 05",
         "numberCode": 3005,
         "GMF_LAT": "Cökszan",
         "GMF_CYR": "Чӧксан",
         "MQY_KMS": "爍山灣",
         "MQY_HGL": "쓱찬·깐",
         "MQY_LAT": "Zvg Jaan Qan"},
        {"id": "LSO_06",
         "displayCode": "LSO 06",
         "numberCode": 3006,
         "GMF_LAT": "Jüxndajqo",
         "GMF_CYR": "Йӱъндайӄо",
         "MQY_KMS": "淵底河",
         "MQY_HGL": "윤댜.호.",
         "MQY_LAT": "Yun Dyar Hor"},
        {"id": "LSO_07",
         "displayCode": "LSO 07",
         "numberCode": 3007,
         "GMF_LAT": "Àtaw",
         "GMF_CYR": "Аътаў",
         "MQY_KMS": "丫頭",
         "MQY_HGL": "아타.",
         "MQY_LAT": "A Tar"},
        {"id": "LSO_08",
         "displayCode": "LSO 08",
         "numberCode": 3008,
         "GMF_LAT": "Sapmàwpyŋ",
         "GMF_CYR": "Шапмаъўпың",
         "MQY_KMS": "十畝坪",
         "MQY_HGL": "삽.마.핑.",
         "MQY_LAT": "Sabr Mar Pingr"},
        {"id": "LSO_09",
         "displayCode": "LSO 09",
         "numberCode": 3009,
         "GMF_LAT": "Öŋpyŋ",
         "GMF_CYR": "Ӧңпың",
         "MQY_KMS": "陽平",
         "MQY_HGL": "응핑",
         "MQY_LAT": "Vng Ping"},
        {"id": "LSO_10",
         "displayCode": "LSO 10",
         "numberCode": 3010,
         "GMF_LAT": "Esztet ə'Gàmwo",
         "GMF_CYR": "Естет ә'Гаъмўо",
         "MQY_KMS": "金禾新邨",
         "MQY_HGL": "금꼬.산쑨",
         "MQY_LAT": "Gvm Qor San Zun"},
        {"id": "LSO_11",
         "displayCode": "LSO 11",
         "numberCode": 3011,
         "GMF_LAT": "Gawwaj",
         "GMF_CYR": "Гаўўай",
         "MQY_KMS": "舊圍",
         "MQY_HGL": "가.꺄.",
         "MQY_LAT": "Gar Qyar"},
        {"id": "LSO_12",
         "displayCode": "LSO 12",
         "numberCode": 3012,
         "GMF_LAT": "Ulej",
         "GMF_CYR": "Улей",
         "MQY_KMS": "湖里",
         "MQY_HGL": "우.러:",
         "MQY_LAT": "Ur Leer"},
        {"id": "LSO_13",
         "displayCode": "LSO 13",
         "numberCode": 3013,
         "GMF_LAT": "Szao",
         "GMF_CYR": "Сао",
         "MQY_KMS": "沙澳",
         "MQY_HGL": "차오.",
         "MQY_LAT": "Ja Or"},
        {"id": "LSO_14",
         "displayCode": "LSO 14",
         "numberCode": 3014,
         "GMF_LAT": "Szao Est",
         "GMF_CYR": "Сао Ешт",
         "MQY_KMS": "沙澳東",
         "MQY_HGL": "차오.동",
         "MQY_LAT": "Ja Or dong"},
        {"id": "LSM_01",
         "displayCode": "LSM 01",
         "numberCode": 4001,
         "GMF_LAT": "Gajmej",
         "GMF_CYR": "Гаймей",
         "MQY_KMS": "雞尾湖",
         "MQY_HGL": "갸머:꾸.",
         "MQY_LAT": "Gya Meer Qur"},
        {"id": "LSM_02",
         "displayCode": "LSM 02",
         "numberCode": 4002,
         "GMF_LAT": "Ùqdərsetþàlə",
         "GMF_CYR": "Уъӄдәршетѳаълә",
         "MQY_KMS": "海底世界",
         "MQY_HGL": "호·댜.서카이.",
         "MQY_LAT": "Hoo Dyar Se Ka Ir"},
        {"id": "LSM_03",
         "displayCode": "LSM 03",
         "numberCode": 4003,
         "GMF_LAT": "Narutəw",
         "GMF_CYR": "Нарутәў",
         "MQY_KMS": "鳴門",
         "MQY_HGL": "밍.문.",
         "MQY_LAT": "Mingr Munr"},
        {"id": "LSM_04",
         "displayCode": "LSM 04",
         "numberCode": 4004,
         "GMF_LAT": "Arzeqt Sawð",
         "GMF_CYR": "Арзеӄт Шаўҙ",
         "MQY_KMS": "銀町南",
         "MQY_HGL": "ᅌᅳᆫ.딩남.",
         "MQY_LAT": "Ngvnr Ding namr"},
        {"id": "LSM_05",
         "displayCode": "LSM 05",
         "numberCode": 4005,
         "GMF_LAT": "Nel ə'Arzeqt",
         "GMF_CYR": "Нел ә'Арзеӄт",
         "MQY_KMS": "銀町",
         "MQY_HGL": "ᅌᅳᆫ.딩",
         "MQY_LAT": "Ngvnr Ding"},
        {"id": "LSM_06",
         "displayCode": "LSM 06",
         "numberCode": 4006,
         "GMF_LAT": "Yksbysəq-bij-Boan",
         "GMF_CYR": "Ыкшбышәӄ-бий-Боан",
         "MQY_KMS": "寶安會展",
         "MQY_HGL": "보·온꾸.친",
         "MQY_LAT": "Boo On Qur Jin"},
        {"id": "LSM_07",
         "displayCode": "LSM 07",
         "numberCode": 4007,
         "GMF_LAT": "Kev ə'Tèrenszoŋ",
         "GMF_CYR": "Кев ә'Теъренсоң",
         "MQY_KMS": "宋宗",
         "MQY_HGL": "쫑송.",
         "MQY_LAT": "Jjong Songr"},
        {"id": "LSM_08",
         "displayCode": "LSM 08",
         "numberCode": 4008,
         "GMF_LAT": "Woŋpyŋ",
         "GMF_CYR": "Ўоңпың",
         "MQY_KMS": "旺坪",
         "MQY_HGL": "꽁.핑.",
         "MQY_LAT": "Qongr Pingr"},
        {"id": "LSM_09",
         "displayCode": "LSM 09",
         "numberCode": 4009,
         "GMF_LAT": "Janmej",
         "GMF_CYR": "Йанмей",
         "MQY_KMS": "欣美",
         "MQY_HGL": "얀머:",
         "MQY_LAT": "Yan Meer"},
        {"id": "LSM_10",
         "displayCode": "LSM 10",
         "numberCode": 4010,
         "GMF_LAT": "Bakwu West",
         "GMF_CYR": "Бакўу Ўешт",
         "MQY_KMS": "白湖西",
         "MQY_HGL": "박꾸.샤",
         "MQY_LAT": "Bag Qur Sya"},
        {"id": "LSM_11",
         "displayCode": "LSM 11",
         "numberCode": 4011,
         "GMF_LAT": "Cekszan",
         "GMF_CYR": "Чексан",
         "MQY_KMS": "赤山",
         "MQY_HGL": "썩.찬·",
         "MQY_LAT": "Zegr Jaan"},
        {"id": "LSM_12",
         "displayCode": "LSM 12",
         "numberCode": 4012,
         "GMF_LAT": "Manjip",
         "GMF_CYR": "Манйип",
         "MQY_KMS": "萬葉",
         "MQY_HGL": "만.입.",
         "MQY_LAT": "Manr Ibr"},
        {"id": "LSM_13",
         "displayCode": "LSM 13",
         "numberCode": 4013,
         "GMF_LAT": "Get ə'Goszan",
         "GMF_CYR": "Гет ә'Госан",
         "MQY_KMS": "高山關",
         "MQY_HGL": "고·찬·ᄸᅡᆫ",
         "MQY_LAT": "Goo Jaan Quan"},
        {"id": "LSM_14",
         "displayCode": "LSM 14",
         "numberCode": 4014,
         "GMF_LAT": "Ŋkàjqa",
         "GMF_CYR": "Ңкаъйӄа",
         "MQY_KMS": "蜈溪下",
         "MQY_HGL": "ᅌᅮ.캬까.",
         "MQY_LAT": "Ngur Kya Qar"},
        {"id": "LSM_15",
         "displayCode": "LSM 15",
         "numberCode": 4015,
         "GMF_LAT": "Esztet ə'Qunwaj",
         "GMF_CYR": "Естет ә'Ӄунўай",
         "MQY_KMS": "雄偉邨",
         "MQY_HGL": "훙까쑨",
         "MQY_LAT": "Hung Qa Zun"},
        {"id": "LSM_16",
         "displayCode": "LSM 16",
         "numberCode": 4016,
         "GMF_LAT": "Fałszvułkeq",
         "GMF_CYR": "Фаљсвуљкеӄ",
         "MQY_KMS": "假火山",
         "MQY_HGL": "가포찬·",
         "MQY_LAT": "Ga Po Jaan"},
        {"id": "LSM_17",
         "displayCode": "LSM 17",
         "numberCode": 4017,
         "GMF_LAT": "Jəxktin",
         "GMF_CYR": "Йәъктин",
         "MQY_KMS": "沃田",
         "MQY_HGL": "육틴.",
         "MQY_LAT": "Yug Tinr"},
        {"id": "LSM_18",
         "displayCode": "LSM 18",
         "numberCode": 4018,
         "GMF_LAT": "Qalöŋwaj",
         "GMF_CYR": "Ӄалӧңўай",
         "MQY_KMS": "夏涼圍",
         "MQY_HGL": "하.릉.꺄.",
         "MQY_LAT": "Har Lvngr Qyar"},
        {"id": "LSM_19",
         "displayCode": "LSM 19",
         "numberCode": 4019,
         "GMF_LAT": "Cojan",
         "GMF_CYR": "Чойан",
         "MQY_KMS": "彩雲",
         "MQY_HGL": "쪼·깐.",
         "MQY_LAT": "Jjoo Qanr"},
        {"id": "LSM_20",
         "displayCode": "LSM 20",
         "numberCode": 4020,
         "GMF_LAT": "Gəkwan",
         "GMF_CYR": "Гәкўан",
         "MQY_KMS": "菊灣",
         "MQY_HGL": "극깐",
         "MQY_LAT": "Gvg Qan"},
        {"id": "LSM_21",
         "displayCode": "LSM 21",
         "numberCode": 4021,
         "GMF_LAT": "Vuðaləqh",
         "GMF_CYR": "Вуҙаләӄь",
         "MQY_KMS": "釋迦牟尼樂園",
         "MQY_HGL": "식야무.너.록윤.",
         "MQY_LAT": "Sig Ya Mur Ner Log Yunr"},
        {"id": "LSM_22",
         "displayCode": "LSM 22",
         "numberCode": 4022,
         "GMF_LAT": "Grot Yksbysəq Qol",
         "GMF_CYR": "Грот Ыкшбышәӄ Ӄол",
         "MQY_KMS": "展覽大堂",
         "MQY_HGL": "친람댜통.",
         "MQY_LAT": "Jin Lam Dya Tongr"},
        {"id": "LSM_23",
         "displayCode": "LSM 23",
         "numberCode": 4023,
         "GMF_LAT": "Szajmej",
         "GMF_CYR": "Саймей",
         "MQY_KMS": "西尾",
         "MQY_HGL": "샤머:",
         "MQY_LAT": "Sya Meer"},
        {"id": "SVP_01",
         "displayCode": "SVP 01",
         "numberCode": 5001,
         "GMF_LAT": "Kev ə'Tèrenszoŋ",
         "GMF_CYR": "Кев ә'Теъренсоң",
         "MQY_KMS": "宋宗",
         "MQY_HGL": "쫑송.",
         "MQY_LAT": "Jjong Songr"},
        {"id": "SVP_02",
         "displayCode": "SVP 02",
         "numberCode": 5002,
         "GMF_LAT": "Cojan",
         "GMF_CYR": "Чойан",
         "MQY_KMS": "彩雲",
         "MQY_HGL": "쪼·깐.",
         "MQY_LAT": "Jjoo Qanr"},
        {"id": "SVP_03",
         "displayCode": "SVP 03",
         "numberCode": 5003,
         "GMF_LAT": "Gəkwan",
         "GMF_CYR": "Гәкўан",
         "MQY_KMS": "菊灣",
         "MQY_HGL": "극깐",
         "MQY_LAT": "Gvg Qan"},
        {"id": "SVP_04",
         "displayCode": "SVP 04",
         "numberCode": 5004,
         "GMF_LAT": "Pleqhevəq",
         "GMF_CYR": "Плеӄьевәӄ",
         "MQY_KMS": "空港",
         "MQY_HGL": "훙강:",
         "MQY_LAT": "Hung Gaangr"},
        {"id": "LMD_01",
         "displayCode": "LMD 01",
         "numberCode": 6001,
         "GMF_LAT": "Kev ə'Tèrenszoŋ",
         "GMF_CYR": "Кев ә'Теъренсоң",
         "MQY_KMS": "宋宗",
         "MQY_HGL": "쫑송.",
         "MQY_LAT": "Jjong Songr"},
        {"id": "LMD_02",
         "displayCode": "LMD 02",
         "numberCode": 6002,
         "GMF_LAT": "Qənszazjəj",
         "GMF_CYR": "Ӄәнсазйәй",
         "MQY_KMS": "恒沙咀",
         "MQY_HGL": "항.차써.",
         "MQY_LAT": "Hangr Ja Zer"},
        {"id": "LMD_03",
         "displayCode": "LMD 03",
         "numberCode": 6003,
         "GMF_LAT": "Woŋpyŋ",
         "GMF_CYR": "Ўоңпың",
         "MQY_KMS": "旺坪",
         "MQY_HGL": "꽁.핑.",
         "MQY_LAT": "Qongr Pingr"},
        {"id": "LMD_04",
         "displayCode": "LMD 04",
         "numberCode": 6004,
         "GMF_LAT": "Janmej",
         "GMF_CYR": "Йанмей",
         "MQY_KMS": "欣美",
         "MQY_HGL": "얀머:",
         "MQY_LAT": "Yan Meer"},
        {"id": "LMD_05",
         "displayCode": "LMD 05",
         "numberCode": 6005,
         "GMF_LAT": "Bàkwu",
         "GMF_CYR": "Баъкўу",
         "MQY_KMS": "白湖",
         "MQY_HGL": "박꾸.",
         "MQY_LAT": "Bag Qur"},
        {"id": "LMD_06",
         "displayCode": "LMD 06",
         "numberCode": 6006,
         "GMF_LAT": "Tinsaw",
         "GMF_CYR": "Тиншаў",
         "MQY_KMS": "天秀",
         "MQY_HGL": "틴사.",
         "MQY_LAT": "Tin Sar"},
        {"id": "LMD_07",
         "displayCode": "LMD 07",
         "numberCode": 6007,
         "GMF_LAT": "Ŋxlöŋ",
         "GMF_CYR": "Ңълӧң",
         "MQY_KMS": "午亮",
         "MQY_HGL": "ᅌᅮ릉.",
         "MQY_LAT": "Ngu Lvngr"},
        {"id": "LMD_08",
         "displayCode": "LMD 08",
         "numberCode": 6008,
         "GMF_LAT": "Wujgoŋ",
         "GMF_CYR": "Ўуйгоң",
         "MQY_KMS": "回崗",
         "MQY_HGL": "꼬.공",
         "MQY_LAT": "Qor Gong"},
        {"id": "LMD_09",
         "displayCode": "LMD 09",
         "numberCode": 6009,
         "GMF_LAT": "Wòŋtin",
         "GMF_CYR": "Ўоъңтин",
         "MQY_KMS": "黃田",
         "MQY_HGL": "꽁.틴.",
         "MQY_LAT": "Qongr Tinr"},
        {"id": "LMD_10",
         "displayCode": "LMD 10",
         "numberCode": 6010,
         "GMF_LAT": "Nel ə'Ŋawmej",
         "GMF_CYR": "Нел ә'Ңаўмей",
         "MQY_KMS": "牛尾市",
         "MQY_HGL": "ᅌᅡ.머:치",
         "MQY_LAT": "Ngar Meer Ji"},
        {"id": "LMD_11",
         "displayCode": "LMD 11",
         "numberCode": 6011,
         "GMF_LAT": "Dyŋqin",
         "GMF_CYR": "Дыңӄин",
         "MQY_KMS": "鼎軒",
         "MQY_HGL": "딩힌",
         "MQY_LAT": "Ding Hin"},
        {"id": "LMD_12",
         "displayCode": "LMD 12",
         "numberCode": 6012,
         "GMF_LAT": "Öŋpyŋ",
         "GMF_CYR": "Ӧңпың",
         "MQY_KMS": "陽平",
         "MQY_HGL": "응핑",
         "MQY_LAT": "Vng Ping"},
        {"id": "LMD_13",
         "displayCode": "LMD 13",
         "numberCode": 6013,
         "GMF_LAT": "Maŋfo",
         "GMF_CYR": "Маңфо",
         "MQY_KMS": "孟火山",
         "MQY_HGL": "망.포짠",
         "MQY_LAT": "Mangr Po Jjan"},
        {"id": "LMD_Q1",
         "displayCode": "LMD Q1",
         "numberCode": 6101,
         "GMF_LAT": "Qorsləqt",
         "GMF_CYR": "Ӄоршләӄт",
         "MQY_KMS": "賽馬場",
         "MQY_HGL": "쌰마쓴.",
         "MQY_LAT": "Zya Ma Zvnr"},
        {"id": "LMD_14",
         "displayCode": "LMD 14",
         "numberCode": 6014,
         "GMF_LAT": "Jünivèrsytþi ə'C.J.M.",
         "GMF_CYR": "Йӱнивеършытѳи ә'Ч.Й.М.",
         "MQY_KMS": "陳宇文유니바·시.티.",
         "MQY_HGL": "짠유마/유니바·",
         "MQY_LAT": "Jjan Yu Manr/UNB"},
        {"id": "LMD_15",
         "displayCode": "LMD 15",
         "numberCode": 6015,
         "GMF_LAT": "Tawq wð'Ajðiə",
         "GMF_CYR": "Таўӄ ўҙ'Айҙиә",
         "MQY_KMS": "新概鎮",
         "MQY_HGL": "산쿄.짠",
         "MQY_LAT": "San Kyor Jjan"},
        {"id": "LMD_16",
         "displayCode": "LMD 16",
         "numberCode": 6016,
         "GMF_LAT": "Batfuŋ",
         "GMF_CYR": "Батфуң",
         "MQY_KMS": "八鳳凹",
         "MQY_HGL": "받풍.아·",
         "MQY_LAT": "Bad Pungr Aa"},
        {"id": "LMD_17",
         "displayCode": "LMD 17",
         "numberCode": 6017,
         "GMF_LAT": "Szanqa",
         "GMF_CYR": "Санӄа",
         "MQY_KMS": "山下",
         "MQY_HGL": "찬·하.",
         "MQY_LAT": "Jaan Har"},
        {"id": "LMD_18",
         "displayCode": "LMD 18",
         "numberCode": 6018,
         "GMF_LAT": "Moŋdej",
         "GMF_CYR": "Моңдей",
         "MQY_KMS": "網地",
         "MQY_HGL": "몽.더.",
         "MQY_LAT": "Mongr Der"},
        {"id": "LMD_A1",
         "displayCode": "LMD A1",
         "numberCode": 6201,
         "GMF_LAT": "Sapjitszün",
         "GMF_CYR": "Шапйитсӱн",
         "MQY_KMS": "十二村",
         "MQY_HGL": "삽.니.쭌",
         "MQY_LAT": "Sabr Nir Jjun"},
        {"id": "LMD_A2",
         "displayCode": "LMD A2",
         "numberCode": 6202,
         "GMF_LAT": "Szèktin",
         "GMF_CYR": "Сеъктин",
         "MQY_KMS": "石田",
         "MQY_HGL": "척틴.",
         "MQY_LAT": "Jeg Tinr"},
        {"id": "LMD_A3",
         "displayCode": "LMD A3",
         "numberCode": 6203,
         "GMF_LAT": "Tszöŋwaj",
         "GMF_CYR": "Тсӧңўай",
         "MQY_KMS": "昌圍",
         "MQY_HGL": "씅까",
         "MQY_LAT": "Zvng Qaj"},
        {"id": "LMD_A4",
         "displayCode": "LMD A4",
         "numberCode": 6204,
         "GMF_LAT": "Qinma",
         "GMF_CYR": "Ӄинма",
         "MQY_KMS": "牽馬",
         "MQY_HGL": "힌마·깐",
         "MQY_LAT": "Hin Maa Qan"},
        {"id": "LZT_01",
         "displayCode": "LZT 01",
         "numberCode": 7001,
         "GMF_LAT": "Lek ə'Sałtþ",
         "GMF_CYR": "Лек ә'Шаљтѳ",
         "MQY_KMS": "鹽湖",
         "MQY_HGL": "임.우.",
         "MQY_LAT": "Imr Ur"},
        {"id": "LZT_02",
         "displayCode": "LZT 02",
         "numberCode": 7002,
         "GMF_LAT": "Qàwpo",
         "GMF_CYR": "Ӄаъўпо",
         "MQY_KMS": "後浦",
         "MQY_HGL": "하:포.",
         "MQY_LAT": "Haar Por"},
        {"id": "LZT_03",
         "displayCode": "LZT 03",
         "numberCode": 7003,
         "GMF_LAT": "Sàmtszon",
         "GMF_CYR": "Шаъмтсон",
         "MQY_KMS": "三壯",
         "MQY_HGL": "삼쏭.",
         "MQY_LAT": "Sam Zongr"},
        {"id": "LZT_04",
         "displayCode": "LZT 04",
         "numberCode": 7004,
         "GMF_LAT": "Sàmwan",
         "GMF_CYR": "Шаъмўан",
         "MQY_KMS": "深灣",
         "MQY_HGL": "삼깐",
         "MQY_LAT": "Sam Qan"},
        {"id": "LZT_05",
         "displayCode": "LZT 05",
         "numberCode": 7005,
         "GMF_LAT": "Sapmàwpyŋ",
         "GMF_CYR": "Шапмаъўпың",
         "MQY_KMS": "十畝坪",
         "MQY_HGL": "삽.마.핑.",
         "MQY_LAT": "Sabr Mar Pingr"},
        {"id": "LZT_06",
         "displayCode": "LZT 06",
         "numberCode": 7006,
         "GMF_LAT": "Fùŋa",
         "GMF_CYR": "Фуъңа",
         "MQY_KMS": "虎牙",
         "MQY_HGL": "푸ᅌᅡ.찬·",
         "MQY_LAT": "Pu Ngar Jaan"},
        {"id": "LZT_07",
         "displayCode": "LZT 07",
         "numberCode": 7007,
         "GMF_LAT": "Ŋàŋsek",
         "GMF_CYR": "Ңаъңшек",
         "MQY_KMS": "硬石",
         "MQY_HGL": "ᅌᅡᆼ.척.찬·",
         "MQY_LAT": "Ngangr Jegr Jaan"},
        {"id": "LZT_08",
         "displayCode": "LZT 08",
         "numberCode": 7008,
         "GMF_LAT": "Wàpyŋ",
         "GMF_CYR": "Ўаъпың",
         "MQY_KMS": "華坪",
         "MQY_HGL": "까.핑.",
         "MQY_LAT": "Qar Pingr"},
        {"id": "LZT_09",
         "displayCode": "LZT 09",
         "numberCode": 7009,
         "GMF_LAT": "Qaŋlət",
         "GMF_CYR": "Ӄаңләт",
         "MQY_KMS": "坑仔",
         "MQY_HGL": "항쨔.",
         "MQY_LAT": "Hang Jjyar"},
        {"id": "LZT_10",
         "displayCode": "LZT 10",
         "numberCode": 7010,
         "GMF_LAT": "Taŋcuŋ",
         "GMF_CYR": "Таңчуң",
         "MQY_KMS": "騰涌",
         "MQY_HGL": "탕.쭝",
         "MQY_LAT": "Tangr Jjung"},
        {"id": "LZT_11",
         "displayCode": "LZT 11",
         "numberCode": 7011,
         "GMF_LAT": "Dòŋwan",
         "GMF_CYR": "Доъңўан",
         "MQY_KMS": "東灣",
         "MQY_HGL": "동깐.",
         "MQY_LAT": "Dong Qanr"},
        {"id": "LZT_12",
         "displayCode": "LZT 12",
         "numberCode": 7012,
         "GMF_LAT": "Namwan",
         "GMF_CYR": "Намўан",
         "MQY_KMS": "南灣",
         "MQY_HGL": "남.깐.",
         "MQY_LAT": "Namr Qanr"},
        {"id": "LZT_13",
         "displayCode": "LZT 13",
         "numberCode": 7013,
         "GMF_LAT": "Qył ə'Dragəq",
         "GMF_CYR": "Ӄыљ ә'Драгәӄ",
         "MQY_KMS": "飛龍山",
         "MQY_HGL": "퍼·룽.찬·",
         "MQY_LAT": "Pee Lungr Jaan"},
        {"id": "LZT_14",
         "displayCode": "LZT 14",
         "numberCode": 7014,
         "GMF_LAT": "Szyŋdakaw",
         "GMF_CYR": "Сыңдакаў",
         "MQY_KMS": "盛德凹",
         "MQY_HGL": "청.닥아·",
         "MQY_LAT": "Jengr Dag Aa"},
        {"id": "LZT_15",
         "displayCode": "LZT 15",
         "numberCode": 7015,
         "GMF_LAT": "Cỳŋtin",
         "GMF_CYR": "Чыъңтин",
         "MQY_KMS": "青田",
         "MQY_HGL": "징틴.",
         "MQY_LAT": "Xing Tinr"},
        {"id": "LZT_16",
         "displayCode": "LZT 16",
         "numberCode": 7016,
         "GMF_LAT": "Qənszazjəj",
         "GMF_CYR": "Ӄәнсазйәй",
         "MQY_KMS": "恒沙咀",
         "MQY_HGL": "항.차써.",
         "MQY_LAT": "Hangr Ja Zer"},
        {"id": "LZT_17",
         "displayCode": "LZT 17",
         "numberCode": 7017,
         "GMF_LAT": "Woŋpyŋ",
         "GMF_CYR": "Ўоңпың",
         "MQY_KMS": "旺坪",
         "MQY_HGL": "꽁.핑.",
         "MQY_LAT": "Qongr Pingr"},
        {"id": "LZT_18",
         "displayCode": "LZT 18",
         "numberCode": 7018,
         "GMF_LAT": "Janmej",
         "GMF_CYR": "Йанмей",
         "MQY_KMS": "欣美",
         "MQY_HGL": "얀머:",
         "MQY_LAT": "Yan Meer"},
        {"id": "LZT_19",
         "displayCode": "LZT 19",
         "numberCode": 7019,
         "GMF_LAT": "Gàpqo",
         "GMF_CYR": "Гаъпӄо",
         "MQY_KMS": "急河",
         "MQY_HGL": "갑호.",
         "MQY_LAT": "Gab Hor"},
        {"id": "LZT_20",
         "displayCode": "LZT 20",
         "numberCode": 7020,
         "GMF_LAT": "Bakbuj",
         "GMF_CYR": "Бакбуй",
         "MQY_KMS": "白貝",
         "MQY_HGL": "박.뷰",
         "MQY_LAT": "Bagr Byu"},
        {"id": "LZT_21",
         "displayCode": "LZT 21",
         "numberCode": 7021,
         "GMF_LAT": "Gon Pu Qyar",
         "GMF_CYR": "Гон Пу Ӄыар",
         "MQY_KMS": "趕虎圍",
         "MQY_HGL": "곤푸꺄.",
         "MQY_LAT": "Gonfùwaj"},
        {"id": "LZT_22",
         "displayCode": "LZT 22",
         "numberCode": 7022,
         "GMF_LAT": "Lòŋpyŋ",
         "GMF_CYR": "Лоъңпың",
         "MQY_KMS": "朗坪",
         "MQY_HGL": "롱핑.",
         "MQY_LAT": "Long Pingr"},
        {"id": "LZT_23",
         "displayCode": "LZT 23",
         "numberCode": 7023,
         "GMF_LAT": "Bakwan",
         "GMF_CYR": "Бакўан",
         "MQY_KMS": "北環",
         "MQY_HGL": "박깐.",
         "MQY_LAT": "Bag Qanr"},
        {"id": "LZT_24",
         "displayCode": "LZT 24",
         "numberCode": 7024,
         "GMF_LAT": "Dòŋwan",
         "GMF_CYR": "Доъңўан",
         "MQY_KMS": "東環",
         "MQY_HGL": "동깐.",
         "MQY_LAT": "Dong Qanr"},
        {"id": "LZT_25",
         "displayCode": "LZT 25",
         "numberCode": 7025,
         "GMF_LAT": "Szànwan",
         "GMF_CYR": "Саънўан",
         "MQY_KMS": "新環",
         "MQY_HGL": "산깐.",
         "MQY_LAT": "San Qanr"},
        {"id": "LZT_26",
         "displayCode": "LZT 26",
         "numberCode": 7026,
         "GMF_LAT": "Mejszyŋ",
         "GMF_CYR": "Мейсың",
         "MQY_KMS": "美聲",
         "MQY_HGL": "머·싱",
         "MQY_LAT": "Mee Sing"},
        {"id": "LZT_27",
         "displayCode": "LZT 27",
         "numberCode": 7027,
         "GMF_LAT": "Szytikev",
         "GMF_CYR": "Сытикев",
         "MQY_KMS": "城洞",
         "MQY_HGL": "찡.동.",
         "MQY_LAT": "Jjingr Dongr"},
        {"id": "LZT_28",
         "displayCode": "LZT 28",
         "numberCode": 7028,
         "GMF_LAT": "Waŋmaw",
         "GMF_CYR": "Ўаңмаў",
         "MQY_KMS": "宏貿",
         "MQY_HGL": "끙.마·",
         "MQY_LAT": "Qvngr Maa"},
        {"id": "LCJ_01",
         "displayCode": "LCJ 01",
         "numberCode": 7001,
         "GMF_LAT": "Kałcəzowq",
         "GMF_CYR": "Каљчәзоўӄ",
         "MQY_KMS": "文化村",
         "MQY_HGL": "분카.쓴",
         "MQY_LAT": "Bun kar zvn"},
        {"id": "LCJ_02",
         "displayCode": "LCJ 02",
         "numberCode": 7002,
         "GMF_LAT": "Sawðpojqt",
         "GMF_CYR": "Шаўҙпойӄт",
         "MQY_KMS": "陸津南岸",
         "MQY_HGL": "룩.쓴남.온.",
         "MQY_LAT": "Lugr Zvn Namr Onr"},
        {"id": "LCJ_03",
         "displayCode": "LCJ 03",
         "numberCode": 7003,
         "GMF_LAT": "Et Qiro",
         "GMF_CYR": "Ет Ӄиро",
         "MQY_KMS": "八大名",
         "MQY_HGL": "받·댜.밍.",
         "MQY_LAT": "Baad Dyar Mingr"},
        {"id": "LCJ_04",
         "displayCode": "LCJ 04",
         "numberCode": 7004,
         "GMF_LAT": "Ciwqoj",
         "GMF_CYR": "Чиўӄой",
         "MQY_KMS": "朝海",
         "MQY_HGL": "쎠하.",
         "MQY_LAT": "Zye Har"},
        {"id": "LCJ_05",
         "displayCode": "LCJ 05",
         "numberCode": 7005,
         "GMF_LAT": "Wuzrəw",
         "GMF_CYR": "Ўузрәў",
         "MQY_KMS": "木行",
         "MQY_HGL": "목홍.",
         "MQY_LAT": "Mog Hongr"},
        {"id": "LCJ_06",
         "displayCode": "LCJ 06",
         "numberCode": 7006,
         "GMF_LAT": "Jöŋszü",
         "GMF_CYR": "Йӧңсӱ",
         "MQY_KMS": "洋樹",
         "MQY_HGL": "응.추.",
         "MQY_LAT": "Vngr Jur"},
        {"id": "LCJ_07",
         "displayCode": "LCJ 07",
         "numberCode": 7007,
         "GMF_LAT": "Griəqviəłðməq",
         "GMF_CYR": "Гриәӄвиәљҙмәӄ",
         "MQY_KMS": "綠田",
         "MQY_HGL": "륵.틴.",
         "MQY_LAT": "Lvgr Tinr"},
        {"id": "LCJ_08",
         "displayCode": "LCJ 08",
         "numberCode": 7008,
         "GMF_LAT": "Ŋszaw",
         "GMF_CYR": "Ңсаў",
         "MQY_KMS": "五秀",
         "MQY_HGL": "ᅌᅮ사.",
         "MQY_LAT": "Ngu Sar"},
        {"id": "LCJ_09",
         "displayCode": "LCJ 09",
         "numberCode": 7009,
         "GMF_LAT": "Qył ə'Kjoŋsek",
         "GMF_CYR": "Ӄыљ ә'Кйоңшек",
         "MQY_KMS": "礦石山",
         "MQY_HGL": "ᄸᅩᆼ척찬·",
         "MQY_LAT": "Quong Jeg Jaan"},
        {"id": "LCJ_10",
         "displayCode": "LCJ 10",
         "numberCode": 7010,
         "GMF_LAT": "Qowwan",
         "GMF_CYR": "Ӄоўўан",
         "MQY_KMS": "鵠灣",
         "MQY_HGL": "호:깐",
         "MQY_LAT": "Hoor Qan"},
        {"id": "LCJ_11",
         "displayCode": "LCJ 11",
         "numberCode": 7011,
         "GMF_LAT": "Dàkjan",
         "GMF_CYR": "Даъкйан",
         "MQY_KMS": "德仁",
         "MQY_HGL": "닥얀.",
         "MQY_LAT": "Dag Yanr"},
        {"id": "LCJ_12",
         "displayCode": "LCJ 12",
         "numberCode": 7012,
         "GMF_LAT": "Qył ə'Ùdje",
         "GMF_CYR": "Ӄыљ ә'Уъдйе",
         "MQY_KMS": "蝴蝶山",
         "MQY_HGL": "우.둡찬·",
         "MQY_LAT": "Ur Dub Jaan"},
        {"id": "LCJ_13",
         "displayCode": "LCJ 13",
         "numberCode": 7013,
         "GMF_LAT": "Woŋtaw",
         "GMF_CYR": "Ўоңтаў",
         "MQY_KMS": "黃頭",
         "MQY_HGL": "꽁.타.",
         "MQY_LAT": "Qongr Tar"},
        {"id": "LCJ_14",
         "displayCode": "LCJ 14",
         "numberCode": 7014,
         "GMF_LAT": "Cojan",
         "GMF_CYR": "Чойан",
         "MQY_KMS": "彩雲",
         "MQY_HGL": "쪼·깐.",
         "MQY_LAT": "Jjoo Qanr"},
        {"id": "LCJ_15",
         "displayCode": "LCJ 15",
         "numberCode": 7015,
         "GMF_LAT": "LCJ 15",
         "GMF_CYR": "ЛЧЙ 15",
         "MQY_KMS": "LCJ 15",
         "MQY_HGL": "어르.시써·삽.ᅌᅮ",
         "MQY_LAT": "E Lvr Si Zee 15"},
        {"id": "LCJ_16",
         "displayCode": "LCJ 16",
         "numberCode": 7016,
         "GMF_LAT": "Fuŋmej",
         "GMF_CYR": "Фуңмей",
         "MQY_KMS": "鳳尾山",
         "MQY_HGL": "풍머:찬·",
         "MQY_LAT": "Pung Meer Jaan"},
        {"id": "LLC_01",
         "displayCode": "LLC 01",
         "numberCode": 9001,
         "GMF_LAT": "Nel əð'Kwiq",
         "GMF_CYR": "Нел әҙ'Кўиӄ",
         "MQY_KMS": "皇后町",
         "MQY_HGL": "꽁하.딩",
         "MQY_LAT": "Qong Har Ding"},
        {"id": "LLC_02",
         "displayCode": "LLC 02",
         "numberCode": 9002,
         "GMF_LAT": "Nel ə'Jüman",
         "GMF_CYR": "Нел ә'Йӱман",
         "MQY_KMS": "漁民町",
         "MQY_HGL": "유.만.딩",
         "MQY_LAT": "Yur Manr Ding"},
        {"id": "LLC_03",
         "displayCode": "LLC 03",
         "numberCode": 9003,
         "GMF_LAT": "Et Qiro",
         "GMF_CYR": "Ет Ӄиро",
         "MQY_KMS": "八大名",
         "MQY_HGL": "받·댜.밍.",
         "MQY_LAT": "Baad Dyar Mingr"},
        {"id": "LLC_04",
         "displayCode": "LLC 04",
         "numberCode": 9004,
         "GMF_LAT": "Qinqok",
         "GMF_CYR": "Ӄинӄок",
         "MQY_KMS": "蜆殼灣",
         "MQY_HGL": "힌혹.깐",
         "MQY_LAT": "Hin Hogr Qan"},
        {"id": "LLC_05",
         "displayCode": "LLC 05",
         "numberCode": 9005,
         "GMF_LAT": "Joŋjügwan",
         "GMF_CYR": "Йоңйӱгўан",
         "MQY_KMS": "鱅魚灣",
         "MQY_HGL": "용유.ᄸᅡᆫ",
         "MQY_LAT": "Yong Yur Quan"},
        {"id": "LLC_06",
         "displayCode": "LLC 06",
         "numberCode": 9006,
         "GMF_LAT": "Edwałtəq",
         "GMF_CYR": "Едўаљтәӄ",
         "MQY_KMS": "익까.",
         "MQY_HGL": "익까.",
         "MQY_LAT": "Ig Qar"},
        {"id": "LLC_07",
         "displayCode": "LLC 07",
         "numberCode": 9007,
         "GMF_LAT": "Kajjan",
         "GMF_CYR": "Каййан",
         "MQY_KMS": "啟仁",
         "MQY_HGL": "캬얀",
         "MQY_LAT": "Kya Yan"},
        {"id": "LLC_08",
         "displayCode": "LLC 08",
         "numberCode": 9008,
         "GMF_LAT": "Szòwqoqaw",
         "GMF_CYR": "Соъўӄоӄаў",
         "MQY_KMS": "掃河口",
         "MQY_HGL": "수꼬.까.",
         "MQY_LAT": "Su Qor Qar"},
        {"id": "LLC_09",
         "displayCode": "LLC 09",
         "numberCode": 9009,
         "GMF_LAT": "Lokqoj",
         "GMF_CYR": "Локӄой",
         "MQY_KMS": "綠海",
         "MQY_HGL": "륵.호.",
         "MQY_LAT": "Lvgr Hor"},
        {"id": "LLC_10",
         "displayCode": "LLC 10",
         "numberCode": 9010,
         "GMF_LAT": "Qənszazjəj",
         "GMF_CYR": "Ӄәнсазйәй",
         "MQY_KMS": "恒沙咀",
         "MQY_HGL": "항.차써.",
         "MQY_LAT": "Hangr Ja Zer"},
        {"id": "LLC_11",
         "displayCode": "LLC 11",
         "numberCode": 9011,
         "GMF_LAT": "ð'Gartəq",
         "GMF_CYR": "ҙ'Гартәӄ",
         "MQY_KMS": "花園",
         "MQY_HGL": "파윤.",
         "MQY_LAT": "Pa Yunr"},
        {"id": "LLC_12",
         "displayCode": "LLC 12",
         "numberCode": 9012,
         "GMF_LAT": "Jünivèrsytþi ə'Lokcəxn",
         "GMF_CYR": "Йӱнивеършытѳи ә'Локчәън",
         "MQY_KMS": "陸津유니바·시.티.",
         "MQY_HGL": "룩.쓰/유니바·",
         "MQY_LAT": "Lugr Zvn/UNB"},
        {"id": "LLC_13",
         "displayCode": "LLC 13",
         "numberCode": 9013,
         "GMF_LAT": "Sytadel ə'Lokcəxn",
         "GMF_CYR": "Шытадел ә'Локчәън",
         "MQY_KMS": "陸津城寨",
         "MQY_HGL": "룩.쓴찡.짜·",
         "MQY_LAT": "Lugr Zvn Jjingr Jjaa"},
        {"id": "LLC_14",
         "displayCode": "LLC 14",
         "numberCode": 9014,
         "GMF_LAT": "Szàmsza",
         "GMF_CYR": "Саъмса",
         "MQY_KMS": "深沙",
         "MQY_HGL": "참차",
         "MQY_LAT": "Jam Ja"},
        {"id": "LLC_15",
         "displayCode": "LLC 15",
         "numberCode": 9015,
         "GMF_LAT": "Wyŋqyŋ",
         "GMF_CYR": "Ўыңӄың",
         "MQY_KMS": "永興",
         "MQY_HGL": "낑.힝",
         "MQY_LAT": "Qingr Hing"},
        {"id": "LLC_16",
         "displayCode": "LLC 16",
         "numberCode": 9016,
         "GMF_LAT": "Titszan",
         "GMF_CYR": "Титсан",
         "MQY_KMS": "鐵山",
         "MQY_HGL": "턷찬·",
         "MQY_LAT": "Ted Jaan"},
        {"id": "LLC_17",
         "displayCode": "LLC 17",
         "numberCode": 9017,
         "GMF_LAT": "Loŋwaj",
         "GMF_CYR": "Лоңўай",
         "MQY_KMS": "狼圍",
         "MQY_HGL": "롱.꺄.",
         "MQY_LAT": "Longr Qyar"},
        {"id": "LLC_18",
         "displayCode": "LLC 18",
         "numberCode": 9018,
         "GMF_LAT": "Fatqöŋ",
         "GMF_CYR": "Фатӄӧң",
         "MQY_KMS": "佛鄉",
         "MQY_HGL": "팓.흥",
         "MQY_LAT": "Padr Hvng"},
        {"id": "LLC_19",
         "displayCode": "LLC 19",
         "numberCode": 9019,
         "GMF_LAT": "Esztet ə'Qunwaj",
         "GMF_CYR": "Естет ә'Ӄунўай",
         "MQY_KMS": "雄偉邨",
         "MQY_HGL": "훙까쑨",
         "MQY_LAT": "Hung Qa Zun"},
        {"id": "LLC_20",
         "displayCode": "LLC 20",
         "numberCode": 9020,
         "GMF_LAT": "Ŋkàjqa",
         "GMF_CYR": "Ңкаъйӄа",
         "MQY_KMS": "蜈溪下",
         "MQY_HGL": "ᅌᅮ.캬까.",
         "MQY_LAT": "Ngur Kya Qar"}
    ],
    createDropdownEntry: function(station) {
        var dropdownEntry = document.createElement("option")
        makeElementAndAttach(
            document.getElementById("station-select"),
            "option", station.GMF_LAT, station.id + "_dropdown")},
    createTableRow: function(station) {
        var rowElement = document.createElement("tr")
        rowElement.setAttribute("id", "ROW_" + station.id)
        // Name columns
        var nameColumns = ["displayCode", "GMF_LAT", "GMF_CYR",
                           "MQY_KMS", "MQY_HGL", "MQY_LAT"]

        for (i in nameColumns) {
            makeElementAndAttach(rowElement,
                                 "td",
                                 station[nameColumns[i]])}
        // Fare columns
        var fareColumns = ["cardStd", "cardCon", "cardEld",
                           "cashStd", "cashCon"]
        for (i in fareColumns) {
            makeElementAndAttach(
                rowElement,
                "td",
                "---",
                station.id + "_" + fareColumns[i])}
        document.getElementById("destination-list").appendChild(rowElement)}};

// main function
var farefinder = {
    // currency units in millipence
    harbourPenalty: 8000,
    stationPenaltyShort: 2500,
    stationPenaltyMedium: 4500,
    stationPenalty: 7000,
    airport: 84000,
    border: 34500,
    quantum: 50,

    cardDiscount: 0.95,
    elderlyFixed: 2000,
    childDiscount: 0.45,

    formatCurrency: function(millipence) {
        rmd = millipence - ((millipence % farefinder.quantum < 1)
                            ? 0
                            : (millipence % farefinder.quantum) - farefinder.quantum);
        shillings  = Math.floor(rmd / 12000);
        pence      = Math.floor((rmd % 12000) / 1000);
        centipence = Math.floor((rmd % 1000) / 10);
        return (shillings + "′ " + pad(pence, 2)
                + "·" + pad(centipence, 2) + "″");},

    distance: function(from, to) {
        // tbd
        return 0;},
    crossHarbourP: function(from, to) {
        // tbd
        return false;},

    writeFares: function(stationId, mainFare) {
        // The main paper fare is just `mainFare'.
        document.getElementById(stationId + "_cashStd").childNodes[0].nodeValue
            = farefinder.formatCurrency(mainFare)
        // The card fare is `mainFare' × `cardDiscount'.
        document.getElementById(stationId + "_cardStd").childNodes[0].nodeValue
            = farefinder.formatCurrency(mainFare * farefinder.cardDiscount)
        // The consessionary paper fare is `mainFare' × `childDiscount'.
        document.getElementById(stationId + "_cashCon").childNodes[0].nodeValue
            = farefinder.formatCurrency(mainFare * farefinder.childDiscount)

        // The consessionary card fare is
        // `mainFare' × `childDiscount' × `cardDiscount'.
        document.getElementById(stationId + "_cardCon").childNodes[0].nodeValue
            = farefinder.formatCurrency(mainFare * farefinder.childDiscount
                                        * farefinder.cardDiscount)

        // The elderly fare is `elderlyFixed',
        // except to the airport and the border station
        // where it is always the consessionary card fare.

        if (stationId !== "SVP_06" && stationId !== "LMD_17") {
            document.getElementById(stationId + "_cardEld")
                .childNodes[0].nodeValue
                = farefinder.formatCurrency(farefinder.elderlyFixed)}
        else {
            document.getElementById(stationId + "_cardEld")
                .childNodes[0].nodeValue
                = farefinder.formatCurrency(mainFare * farefinder.childDiscount
                                            * farefinder.cardDiscount)}
    },

    init: function() {
        for (i in stations.stationList) {
            stations.createDropdownEntry(stations.stationList[i])
            stations.createTableRow(stations.stationList[i])}}};
