#+Title: Relay 10–4
#+Date: 2018-06-03
#+HTML_LINK_UP: index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="../../global/Default.css"/>
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="../../global/org.css"/>
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="../relay.css"/>
#+OPTIONS: title:nil

* Translation
#+BEGIN_short-relay
#+BEGIN_detail-link
[[file:05-talla-torch.txt][Complete torch document]] · [[file:05-talla-Torch4Iso.txt][Gloss]]
#+END_detail-link

#+BEGIN_natlang-name
English
#+END_natlang-name

#+BEGIN_natlang-text
"I know I am skillful." The man who runs the store sneezed. "I stand in the
place that I've always known."

I sadly looked at Sufarar.

"You are friendly. Look at me now."

"I will obey."

"You run this store, and it is difficult. I do not rest, I am always moving. I
am sure this store will never close."

"This store won't close?"

"This store is impossible to close. A demon told me. The curse is great." The
man sneezed.

"While you ran the store, the curse closed it?"

"Unfortunately, the curse demanded for the store to be closed. I'm sure the
curse will not end for a long time! The demon's curse did not exist when I
worked here."
#+END_natlang-text

#+BEGIN_conlang-name
Laikan
#+END_conlang-name

#+BEGIN_conlang-text
"hadiya yau vai; yau na jiyali." ajwa daz, vaun darauniya aa miram. "biya
huzddal, vaun adan hadiya, yau."

ilwa dibb Zuvara baulwi yau.

"lu na viyaz. auv ha, ilwij yawi lu."

"zumiddiya yau."

"darauniya lu aa miram id, ya vi na uduri. adan bauziviya - adan jada humpi
yau. baubbirariyaj miram id; hadiya yau vai."

"baubbirariyaj miram id, zauha a."

"mid baubbirariya hadan miram id. yigai ajma augu dau. unvaun na lazai." ajwa
 daz.

"auv darauniya lu aa miram, bbirarwaj unvaun vai, yauha a."

"ubbyi unvaun vai; bbirariya ajal miram. auv daam madzi, bauniyinyij unvaun;
 hadiya yau vai. auv gariya yau iddal, bauhiya unvaun ajmahigza augu."
#+END_conlang-text

#+END_short-relay

* Gloss, IPA and Translation
#+BEGIN_EXAMPLE
*************************

ENG TRS: "I know I am skillful." The man who runs the store sneezed. "I stand in the place that I've always known." 
WIZ GLS: know-STA 1S.NOM 3Si.ACC; 1S.NOM have skill."  sneeze-ATEL man, REL.does control-STA ACC store. "stand-STA place-INE, REL.do HAB  know-STA, 1S.NOM."
WIZ TRS: "hadiya  yau    vai;     yau    na   jiyali." ajwa        daz, vaun     darauniya   aa  miram. "biya      huzddal,   vaun   adan hadiya,   yau."

WIZ: "hadiya yau vai; yau na jiyali." ajwa daz, vaun darauniya aa miram. "biya huzddal, vaun adan hadiya, yau."
IPA: ["ɣə̤ˈdijə ˈjɑ ˈvai̯; ˈjɑ nə ʒɪˈjali." ˈaʒwə ˈdaz, ˈvɑn dəɾɑˈnijə ˈe ˈmiɾəm. "ˈbijə ˈɣɯ̤zˌtal, vɑn ˈadən ɣə̤ˈdijə, jɑ."]

*************************

ENG TRS: I sadly looked at Sufarar.
WIZ GLS: look-ATEL sad  Sufarar HON-LAT 1S.NOM.
WIZ TRS: ilwa      dibb Zuvara  baulwi  yau.

WIZ: ilwa dibb Zuvara baulwi yau.
IPA: [ˈilwə ˈdip ˈzɯvəɾə ˈbɑlwi jɑ.]

*************************

ENG TRS: "You are friendly. Look at me now."
WIZ GLS: 2.NOM have kind.  During present, look-TEL-IRR 1S.ADP-LAT 2S.NOM.
WIZ TRS: "lu   na   viyaz. auv    ha,      ilwij        yawi       lu.

WIZ: "lu na viyaz. auv ha, ilwij yawi lu."
IPA: [ˈlɯ nə ˈvijəz. ˈɑv ˈɣa̤, ˈilwiʒ ˈjawi lɯ.]

*************************

ENG TRS: "I will obey."
WIZ GLS: obey-STA   1S.NOM
WIZ TRS: "zumiddiya yau."

WIZ: "zumiddiya yau."
IPA: ["ˈzɯmɪˌdijə jɑ."]

*************************

ENG TRS: "You run this store, and it is difficult. I do not rest, I am always moving. I am sure this store will never close."
WIZ GLS: control-STA 2S.NOM ACC store PROX, and 3Si.NOM have difficult. HAB  NEG-rest-STA - HAB  move-DUR always 1S.NOM. NEG-close-STA-IRR store PROX; know-STA 1S.NOM 3Si.ACC.
WIZ TRS: "darauniya  lu     aa  miram id,   ya  vi      na   uduri.     adan bauziviya    - adan jada     humpi  yau.    baubbirariyaj     miram id;   hadiya   yau    vai."

WIZ: "darauniya lu aa miram id, ya vi na uduri. adan bauziviya - adan jada humpi yau. baubbirariyaj miram id; hadiya yau vai."
IPA: ["dəˈɾɑˌnijə ˈlɯ ˈe ˈmiɾəm ˈid, jə ˈvi nə ˈɯdɯɾi. əˈdan ˈʒadə ˈɣɯ̤mpi ˈjɑ. bɑˈpiɾəˌɾijəʒ ˈmiɾəm ˈid; ɣə̤ˈdijə ˈjɑ ˈvai̯."]

*************************

ENG TRS: "This store won't close?"7
WIZ GLS: NEG-close-STA-IRR store this, yes   Q.
WIZ TRS: "baubbirariyaj    miram id,   zauha a."

WIZ: "baubbirariyaj miram id, zauha a."
IPA: ["bɑˈpiɾəˌɾijəʒ ˈmiɾəm ˈid, ˈzɑɦɑ̤ ˈa."]

*************************

ENG TRS: "This store is impossible to close. A demon told me. The curse is great." The man sneezed.
WIZ GLS: POT NEG-close-STA sure  store PROX. speak-TEL spirit bad  1S.ACC. curse  have great." sneeze-ATEL man.
WIZ TRS: mid baubbirariya  hadan miram id.   yigai     ajma   augu dau.    unvaun na   lazai." ajwa        daz.

WIZ: "mid baubbirariya hadan miram id. yigai ajma augu dau. unvaun na lazai." ajwa daz.
IPA: ["ˈmid bɑˈpiɾəˌɾijə ˈɣadən ˈmiɾəm ˈid. jɪˈɡai̯ ˈaʒmə ˈɑɡɯ ˈdɑ. ˈɯnvɑn nə ləˈzai̯." ˈaʒwə ˈdaz.]

*************************

ENG TRS: "While you ran the store, the curse closed it?"
WIZ GLS: During control-STA 2S.NOM ACC store, close-TEL-IRR curse  3Si.ACC, yes   Q?
WIZ TRS: "auv   darauniya   lu     aa  miram, bbirarwaj     unvaun vai,     yauha a."

WIZ: "auv darauniya lu aa miram, bbirarwaj unvaun vai, yauha a."
IPA: ["ˈɑv dəˈɾɑˌnijə ˈlɯ ˈe ˈmiɾəm, ˈpiɾəɾwəʒ ˈɯnvɑn ˈvai̯, ˈjɑɦə̤ ˈa."]

**************************

ENG TRS: "Unfortunately, the curse demanded for the store to be closed. I'm sure the curse will not end for a long time! The demon's curse did not exist when I worked here."
WIZ GLS: demand-TEL  curse  3Si.ACC; close-STA must store. during time much,  NEG-end-TEL-IRR curse;  know-STA 1S.NOM 3Si.ACC. during work-STA 1S.NOM here-INE, NEG-exist-STA curse  spirit-ABL bad.  
WIZ TRS: "ubbyi      unvaun vai;     bbirariya ajal miram. auv    daam madzi, bauniyinyij     unvaun; hadiya   yau    vai.     auv    gariya   yau    iddal,    bauhiya       unvaun ajmahigza  augu.

WIZ: "ubbyi unvaun vai; bbirariya ajal miram. auv daam madzi, bauniyinyij unvaun; hadiya yau vai. auv gariya yau iddal, bauhiya unvaun ajmahigza augu."
IPA: ["ˈɯpji ˈɯnvɑn vai̯; ˈpiɾəˌɾijə ˈaʒəl ˈmiɾəm. ˈɑv ˈdem ˈmadzi, bɑˈnijɪnˌyiʒ ˈɯnvɑn; ɣə̤ˈdijə ˈjɑ ˈvai̯. ˈɑv ɡəˈɾijə jɑ ˈiˌtal, bɑˈɦi̤jə ˈɯnvɑn ˈaʒməˌɦi̤ɡzə ˈɑɡɯ."]

#+END_EXAMPLE


* Lexicon
| Word    | POS   | Gloss                                                           |
|---------+-------+-----------------------------------------------------------------|
| a       | part. | question particle                                               |
| aa      | part. | accusative particle                                             |
| adan    | part. | habitual particle                                               |
| ajal    | mod.  | required, must                                                  |
| ajma    | n.    | spirit                                                          |
| aju     | v.    | sneeze                                                          |
| augu    | mod.  | bad, evil                                                       |
| auv     | part. | when, while, during                                             |
| baul    | hon.  | male honorific, sir, mister                                     |
| bbiraru | v.    | block, close                                                    |
| bu      | v.    | stand                                                           |
| daam    | n.    | period of time                                                  |
| darauna | v.    | control, be over something                                      |
| daz     | n.    | man                                                             |
| gari    | v.    | work, labor                                                     |
| ha      | n.    | now, present moment                                             |
| hadan   | mod.  | sure(ly), definite(ly)                                          |
| hadu    | v.    | know                                                            |
| hi      | v.    | exist, be (usually translated as "there is")                    |
| humbbi  | mod.  | always                                                          |
| huz     | n.    | place, location                                                 |
| id      | mod.  | proximate determiner, this                                      |
| id      | n.    | here (this place)                                               |
| ilu     | v.    | look, see                                                       |
| iyini   | v.    | end, finish                                                     |
| jada    | v.    | move                                                            |
| jiyali  | n.    | skill, talent                                                   |
| lazai   | mod.  | great, awesome, big                                             |
| madzi   | mod.  | much, a lot                                                     |
| mid     | part. | potential mood, (can, could)                                    |
| miram   | n.    | store, shop, market                                             |
| na      | part. | RELATIVIZER: which has; copula for predicate adjective; to have |
| ubbi    | v.    | demand, order                                                   |
| uduri   | mod.  | difficult                                                       |
| unvaun  | n.    | bad luck, curse                                                 |
| vaun    | part. | RELATIVIZER: which does; gnomic mood particle                   |
| viyaz   | mod.  | kind, polite, friendly                                          |
| ya      | conj. | and, also                                                       |
| yiga    | v.    | speak, tell, talk                                               |
| zauha   | intj. | yes                                                             |
| zivi    | v.    | rest, take a break                                              |
| zumidda | v.    | obey, follow                                                    |
| zuvara  | n.    | proper name                                                     |

* Grammar
Wistanian, natively known as "anigalilaun", is an a priori artlang designed for
use in a novel. It is spoken as a majority language on a large island nation
that has been isolated for most of their history in order to protect their most
valuable and dangerous resource: the ajmastone. This is my first conlang, and
has recieved very many dramatic revisions in the past year since I've been
learning more and more about linguistics and the art of language construction.

** Syntax

*** Parts of speech
Wistanian grammarians classify five distinct parts of speech:


- Nouns :: Any word that takes on nominal morphology
           and can act as a subject or object the verb.
- Verbs :: Any word that takes on verbal morphology.
- Modifiers :: Any word that describes or specifies another word.
               There are no morphological distinctions between adjectives and abverbs.
- Particles :: Any word that have a grammatical role,
               rather than a semantic role, and cannot take on any morphology.
- Honorifics :: A polite title used with many proper nouns. 

*** Word order
Wistanain has a predominately Verb-Subject-Object word order, with Oblique
phrases that can come either first in the sentence, last in the sentence, or
immediately after the verb. The location of an oblique depends entirely on the
nature of the phrase and its role in the sentence (e.g., Oblique phrases that
refer to the time in which an action takes place almost always comes first in a
sentence.)

Modifiers come after their head, unless that modifier is a possessive, number,
or color (in which cases, it comes before the noun it modifies).

Particles come first in a noun or verb phrase (before the head and any
modifiers).

Honorifics come immediately after their heads and before any other modifier.

*** Special sentences and phrases
Imperatives are normally Verb-Object-Subject.

Questions are formed with the question particle <a>. Yes/No questions also end
with either <zahau/zau> (yes) or <baun> (no).

Relative clauses begin with either <va> (which is), <na> (which has), or <vaun>
(which does). These can also be used as copula-like words - <va> connects two
nouns; <na> connects a subject with a modifier; <vaun> connects the subject with
a verb.

Noun clauses are typically split into two separate sentences.

** Morphology

*** Nominal morphology

Improper nouns decline for number and position:

#+Caption: Number
| Number | Definition       | Mark           | Gloss |
|--------+------------------+----------------+-------|
| Paucal | one or a few.    | Unmarked.      |       |
| Plural | more than a few. | <-n> or <-an>. | PL    |

#+Caption: Position 
| Number      | Definition     | Mark      | Gloss | Notes                          |
|-------------+----------------+-----------+-------+--------------------------------|
| Inessive    | within or atop | <-ddal>   | INE   |                                |
| Elative     | outside        | <-al>     | ELA   |                                |
| Lative      | to(ward),      | <-wi>     | LAT   | (also used for dative nouns)   |
| Ablative    | away (from),   | <-igza>   | ABL   | (also used for genitive nouns) |
| Adessive    | near           | <-nuz>    | ADE   |                                |
| Distantive  | far away from  | <-bin>    | DTV   |                                |
| Superessive | above          | <-jazid>  | SUPE  |                                |
| Subessive   | under          | <-bbaggu> | SUBE  |                                |
| Antessive   | before/left    | <??>      | ANTE  |                                |
| Postessive  | after/right    | <??>      | POST  |                                |

Note: Proper Nouns, such as the names of individuals and places, do not take on any morpohology. Instead, proper noun morphology is either omitted or placed on an honorific or a dummy pronoun instead.

*** Pronominal Morphology
Pronouns are classified by five persons, two numbers, and four cases. 

- Persons
  - 1st
  - 2nd
  - 3rd animate :: People
  - 3rd inanimate ::  animals, plants, objects, events, phrases
  - 3rd spiritual :: spirits, ajmastones, sacred/traditional objects
- Number
  - Singular
  - Plural
- Cases
  | Nominative   | subject                 | NOM  |
  | Accusative   | object                  | ACC  |
  | Possessive   | genitive                | POSS |
  | Adpositional | conjugated for position | ADP  |

|     | NOM     | ACC     | POSS    | ADP      |
|-----+---------+---------+---------+----------|
| 1S  | <yau>   | <dau>   | <yi>    | <ya->    |
| 1P  | <yaun>  | <daun>  | <yin>   | <yan->   |
|-----+---------+---------+---------+----------|
| 2S  | <lu>    | <luv>   | <luhi>  | <luha->  |
| 2P  | <lun>   | <luvan> | <luhin> | <luhan-> |
|-----+---------+---------+---------+----------|
| 3Sa | <auzi>  | <auzi>  | <zi>    | <za->    |
| 3Pa | <auzin> | <auzin> | <zin>   | <zan->   |
|-----+---------+---------+---------+----------|
| 3Si | <vi>    | <vai>   | <vi>    | <va->    |
| 3Pi | <vin>   | <vain>  | <vin>   | <van->   |
|-----+---------+---------+---------+----------|
| 3Ss | <ja>    | <ja>    | <ji>    | <ja->    |
| 3Ps | <jan>   | <jan>   | <jin>   | <jan->   |

** Verbal Morphology 
Wistanian verbs conjugate for four lexical aspects (Stative , Durative, Telic,
and Atelic) and two moods (Realis and Irrealis)

*** Lexical Aspect
Lexical aspect in Wistanian is different than grammatical aspect in other
languages. Wistanian verbs typically have a very broad definition, and lexical
aspect helps to narrow down that definition.

For example, the verb <bima> refers to the motion of going from a high place to
a lower place. In the Telic, this verb is translated into English as "fall"; in
the atelic, it's translated as "precipitate or any precipitation-like
situation"; in the durative, it means to "descend"; and in the stative, it means
"to have fallen (i.e., to lay on the ground as result of a fall.)" The lexical
aspects are defined as follows:

| Name     | Gloss | Definition                                           |
|----------+-------+------------------------------------------------------|
| Stative  | STA   | The action is unchanging over a long period of time. |
| Durative | DUR   | The action is in progress from one state to another. |
| Telic    | TEL   | The action has a intended endpoint.                  |
| Atelic   | ATEL  | The action does not have an intended endpoint        |

The following table represents the conjugations for each aspect in each of the verb stems (<-a>, <-i>, and <-u>).

|    | STA    | DUR  | TEL   | ATEL  |
|----+--------+------+-------+-------|
| -a | <-iya> | <-a> | <-ai> | <-a>  |
| -i | <-iya> | <-a> | <-yi> | <-ya> |
| -u | <-iya> | <-a> | <-wi> | <-wa> |

**** Mood 

The two Wistanian moods are realis and irrealis, which are defined as follows:

| Name    | Gloss | Definition                                |
|---------+-------+-------------------------------------------|
| Realis  | --    | The action or situation has happened.     |
| Irrelis | IRR   | The action or situation has not happened. |

The realis mood is unmarked. The irrealis mood is marked after the lexical
aspect conjugations with <-j>.

The irrealis mood is used in these situations:

- Actions or situations that will occur in the future.
- Polite requests
- Questions
- Verbs with an epistemic or deontic particle.

** Negation

All words in all parts of speech, including particles, can be negated with the perfix:

<bau(n)->

* Navigation
:PROPERTIES:
:HTML_CONTAINER: footer
:UNNUMBERED: t
:END:

#+BEGIN_EXPORT html
<nav class="linkset">
  <div id="this">
    <div id="sec"><strong>10</strong> Relay</div>
    <div id="chapB"></div>
    <div id="chapA">Part <strong>4</strong></div>
  </div>
  <a href="03a-place.html" id="prev" rel="prev">Previous</a>
  <a href="05-talla.html" id="next" rel="next">Next</a>
</nav>
#+END_EXPORT
