#+Title: Relay 10–7
#+Date: 2018-06-03
#+HTML_LINK_UP: index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="../../global/Default.css"/>
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="../../global/org.css"/>
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="../relay.css"/>
#+OPTIONS: title:nil

* Translation
#+BEGIN_short-relay

#+BEGIN_detail-link
[[file:07-sincy-orajha-relay-packet-1.pdf][Complete torch]]
#+END_detail-link

#+BEGIN_natlang-name
English
#+END_natlang-name

#+BEGIN_natlang-text
“Knowledge has caused me standing here” said [to no object] person, owner of knowledge.

This has caused: (that) nonsense has seen you well.

You are (a) kind (something): you have listened to me.

You must remember that!

The shop was stopped from not working once they went away from the shop.

It has caused the shop to not have shutdown.

They have tried to figure it out.

The shop was not closed(/dead), yes?

It was. It was certainly closed, because angry monsters proclaimed an evil song.

The shop was not working. Because of you, the shop was shut down (by ???), yes?

I will proclaim a song, because I know: Evil is going to be by here (aka nearby).
#+END_natlang-text

#+BEGIN_conlang-name
Orajha
#+END_conlang-name

#+BEGIN_conlang-text
“te źéama jha aava áwúvyja ida nuruge” ta taara tira illava ira ille nuru.

ta źéama ra: ta kúśúma hyripo sja jatlúrúga.

vosja kúllú hida: ta óótema jha aava sja.

siśi urúmmúma ra sja.

ta thara gevénge limútta, śui ta voma pitli néé illa kúllú rúttú illave limútta kalla.

te źéara ta torama néé limúttaga ra.

te kihima zavu raha raha.

úlú ta vora néé toruga limúttaga, hawó.

ta vora. ta taa lááúnggaga réétjuhhu ravviga dźarridjé, júúsitlu ta vora jháá tira toruga ra.

ta vora néé kúllú rúttú tira limútta. úlú júúsitlu sja, te ngihatjama toruga limúttaga kalla, hawó?

taatta aava lááúngga jha, júúsitlu illava jha illa nuruge: votta gevúmale sijanga kúllú réétjuhhu.
#+END_conlang-text

#+END_short-relay

* Lexicon
** Pronouns
#+ATTR_HTML: :class vocablist
- jha :: 1p sg. pronoun
- sja :: 2p sg. pronoun
- ra :: 3p sg. pronoun
- jhahi :: 1p pl. incl. pronoun
- jattei :: 1p pl. excl. pronoun
- sjahi :: 2p pl. pronoun
- raha :: 3p pl. pronoun
- taele :: coll. pronoun (added directly after a singular pronoun to turn it colloquial)

** Nouns
#+ATTR_HTML: :class vocablist
- iraga :: person, individual
- jatlúrúga :: nonsense, gibberish, incomprehensible information
- lááúnggaga :: song, melody, joik; something melodic conveying emotions, performed using a
- voice
- limúttúga :: shop, store, kiosk, booth
- ravviga :: monsters, demons, evil-doers
- sijangaga :: here, the present location
- nuruge :: wisdom; accumulated knowledge
- toruga :: deceased, dead; (contextually) a corpse

** Verbs
#+ATTR_HTML: :class vocablist
- áwúvyma :: to stand (upright)
- kihima :: to figure out, to decipher, to understand
- kúśúma :: to see, to observe
- ngihatjama :: to make, to assemble; to put something in a certain state
- óótema :: to hear, to listen, to register information
- taama :: to speak, to communicate
- thama :: to move, to walk
- torama :: to die, to shut down
- ungirama :: to cease, to stop
- urúmmúma :: to remember, to study
- voma :: to exist; to be (in a certain state)
- źéama :: to cause, to make happen

** Adjectives
#+ATTR_HTML: :class vocablist
- dźarridjé :: angry, raging, infuriated; deeply upset
- hida :: good, nice; viewed as positive
- réétjuhhu :: evil, horrible; bad for the sake of being bad
- rúttú :: working, functioning, taking action

** Adverbs
#+ATTR_HTML: :class vocablist
- hyripo :: properly executed, thorough
- ida :: here, at the current location
- jháá :: very, certainly, undoubtably, obviously
- néé :: not, none
- pitli :: stopped, ceased, stopped, ceased
- zavú :: tried, attempted
- Interjections:
- hewó :: yes, confirmed, affirmative

** Condition markers
#+ATTR_HTML: :class vocablist
- siśi :: imperative
- úlú :: questioning (“has X happened?”)

** Miscellaneous
#+ATTR_HTML: :class vocablist
- kúllú :: dummy word for nounifying adjectives
- tira :: ​dummy word that replaces objects sometimes
- śui :: clause binding thing: “then, after that”
- kalla :: dummy word representing previous events or unknowns acting as subjects &// agents
- júúsitlu :: clause binding thing: “because, due to”

* Grammar
** (Actual) Grammar
Orajha is very head-initial. Adjectives follow the nouns they affect, adverbs
follow the verbs they affect, possessees their possessors, instruments their
users, and in general, there’s a tendency for OS word order with the V stuck in
before whatever’s performing the V. There are strong VOS order
tendencies. Particles are usually sandwiched in between words. There is no
agent/patient marking. In sentences with subjects acting upon themselves or
without an object, the word “tira” takes the object’s spot.

** Phonology
The stuff you’ll be seeing here and the sounds the stuff represents without
influence from other stuff’s sounds:

a [a], á [æ], b [b], d [d], ð/dh [ð], dj [ɟ], dź [d͡ʒ],
e [ɛ], é [e], f [f], g [g], h [x]/[h], i [i], í/y [y]/[ɪ]/[ɨ],[j],
jh [ʝ], k [k], l [l], m [m], n [n], ń [ɲ], ng [ŋ], o [o], ó [ɤ], 
p [p], r [r], s [s], ś [ʃ]/[ɕ], sj [ç], t [t], ​þ/​th [θ],
tj [c], tl [t͡ɬ], ts [t͡s], tś [t͡ʃ], u [ʉ], ú [u], v [v], w [w], z [z], ź [ʒ]/[ʑ]

Vowels can be elongated by duplication, like so:

1. á - ~/æ/~
2. áá - ~/æː/~
3. ááá - ~/æːː/~

ó, that cheeky bastard, does something slightly different... If it’s at the
beginning of a word, it turns into a ~/ø/~ that behaves just like all the other
vowels. Otherwise, it takes the ~/ɤ/~ it already has and adds on a /ø/ which it
keeps elongating, like so:

1. ó - ~/ɤ/~ (if word start: ~/ø/~)
2. óó - ~/ɤ͡ø/~ (if word start: ~/øː/~)
3. óóó - ~/ɤ͡øː/~
4. óóóó - ~/ɤ͡øːː/~

...and so on. Yes, the tie bar is relevant, but you won’t be dealing with that
here so let’s leave it at that.

<y> prefers being called <í> when at the start of a word.

Single letter consonants geminate like this:

1. r - ~/r/~
2. rr - ~/rː/~
3. etc

Dual letter consonants geminate like this:

1. th - ~/θ/~
2. thh - ~/θː/~
3. etc

<g> and <d> only act “normal” at the start of words. Otherwise, they start mixing their voicing,
like so:

1. g - ~/g̚k/~
2. gg - ~/kːː/~
3. d - ~/d̚t/~
4. dd - ~/tːː/~

Basically, ~/k/~ and ~/t/~ have three lengths, the longest one being written as
though it were an elongated version of the consonants’ voiced counterparts.  In
documentation, for example in this document, <V> stands for any vowel (aka
whatever vowel vowel symphony dictates in a spot where there is no other vowel
to begin with). It is not to be confused with <v>, which simply stands for
~/v/~.  In words more than three syllables long, the second-last syllable is
stressed. Otherwise, there is no stress.

*** Vowel harmony
Vowel harmony is pretty simple. A lot of affixes, for example, tend to take on a V vowel - which
is a or e, depending on what the first vowel of the word in question is. Particles take on the V of
the word they’re bound to, regardless if they’re placed before or after it.
| V = a | V = e |
|-------+-------|
| á     | é     |
| o     | ó     |
| ú     | u     |
| i     | í/y   |

** Punctuation..?!
Because Orajh has a wonderfully inconvenient and kinda large set of punctuation thingies
English doesn’t, my very smart solution for the romanization is to use <q> followed by
something resembling the punctuation mark in question to note ... punctuation. Punctuation
involving q’s is to have spaces on either side for clarity.
Long list:
#+ATTR_HTML: :class vocablist
- <qd> (optionally <,>) :: 
     Thing that allows you to breathe for a sec.
     Acts basically the same way as <,> in English.
- <qo> (optionally <.>) :: Full stop that also marks the end of a sentence.
- <qf> :: Name marker. These go in front of names, like so:
          qf Name qf Namesson. 
          One per word/name.
- <q/> (optionally </>) :: 
     “or”, basically.
     It lets you write indefinitely long lists of things/stuff/alternatives/options
     where the reader may choose their favourite(s), or where only
     one option is relevant (but the reader doesn’t get to know which one).
- <qy> :: “and/or”;
          it's like q/ but includes the possibility 
          of more than one option being relevant.
- <q%> (optionally <%>) :: 
     Word compounding thing. Compounds are head-initial, see: grammar.
- <:> :: Works just like in English.

** Verbs
Orajha verbs have some features to indicate time with, but are not very
informative. Agreements with cases surrounding them are handled with pre- and
especially postpositions.

Present: Dictionary “-ma” is removed. The affixes added are:

| hi | Singular | Dual              | Plural  | Colloquial            |
|----+----------+-------------------+---------+-----------------------|
| 1p | -ja      | -ja (prefix: ka)  | -jannú  | téé (apply a pronoun) |
| 2p | -sja     | -sja (prefix: ka) | -sjajha | téé (apply a pronoun) |
| 3p | -ra      | -ra (prefix: ka)  | -rańńi  | téé (apply a pronoun) |

Per default, verbs in the present time are bound to the subject.

- Past :: Dictionary “-ma” is removed.
          Prefix particle “tV” is added.
          Case stuff should bind the verb to a pronoun
          which indicates number and person.
- Perfect past :: Dictionary “-ma” stays.
                  Prefix particle “tV” is added.
                  Case stuff should bind the verb to a pronoun
                  which indicates number and person.
- Future :: Dictionary “-ma” is replaced by “-ttV”.
            Case stuff should bind the verb to a pronoun
            which indicates number and person.
- Perfect future :: Dictionary affix “-ma” is replaced by “-ttV”,
                    prefix particle “tV” is added.
                    Case stuff should bind the verb to a pronoun 
                    which indicates number and person.

** Nouns
The affix -i forms plurals. Non-nominative cases and whatnot are handled by
post- and, especially, prepositions. The dictionary affix of nouns, -gV, is
removed when a particle is added to it. *

** Cases
Hoo boy... ​Orajha has X cases, which can be divided into two categories: Those that have their
own particles (amount), and those that are applied as declinations to the particles the cases with
their own particles create.
#+Caption: Case particles
| hi                       | ∅      | Nominative^{1} | Accusative | Dative | Posessing (genitive) | Posessed Instrument (genitive?) | Instrument user | Instrument |
|--------------------------+--------+----------------+------------+--------+----------------------+---------------------------------+-----------------+------------|
| Sg.                      | wajV   | gevV           | aavV       | uńńV   | illavV               | illV                            | íttV            | itlV       |
| Dual, pl., coll.         | warejV | gelevV         | aavińV     | uńńulV | illééavV             | ijullV                          | ímattV          | ijetlV     |
| Location (Before, After) | B      | B              | A          | A      | B                    | A                               | B               | A          |


Locationey declensions you can put on these poor things:
#+ATTR_HTML: :class vocablist
- -yrú :: Onto   
- -éngV :: Off/Away  
- -yrósV :: On 
- -aritjV :: Under
- -ingú :: Aside  
- -upV :: In   
- -úmalV :: By 
- -inidjV :: With

Note that all particle declension affixes replace the last vowel of the particle
they’re attached to, and that particles are always directly next to the words
they alter.

 ^{1} If a noun has no particles bound to it
and is in the nominative case, the -gV affix is to be left untouched.

Genitive: We mark both the possessor and the possessee. Here’s an example of how this may
be used:

#+BEGIN_EXAMPLE
illava Carl illa Bag - Carl (who happens to own a bag)
illa Bag illava Carl - Bag (that happens to be owned by Carl)
#+END_EXAMPLE


** Nounification?
If you want an adjective to turn into a noun, you slap it onto “kúllú”, which is
just a noun substitute indicating that the following adjective is nounified.

** Condition markers
These are placed at the very beginning of a sentence and “set the mood” for what
is stated in said sentence. They can turn sentences into commands, questions,
&c.

** Other things
a

* Navigation
:PROPERTIES:
:HTML_CONTAINER: footer
:UNNUMBERED: t
:END:

#+BEGIN_EXPORT html
<nav class="linkset">
  <div id="this">
    <div id="sec"><strong>10</strong> Relay</div>
    <div id="chapB"></div>
    <div id="chapA">Part <strong>7</strong></div>
  </div>
  <a href="06-nyar.html" id="prev" rel="prev">Previous</a>
  <a href="08-neo.html" id="next" rel="next">Next</a>
</nav>
#+END_EXPORT

